@startuml DAO Sequence diagram
UI->DAOFactory: create a new DAO
note right
UI passes name, admin, 
token, godHolder
quorumThreshold, votingDelay, votingPeriod
end note
DAOFactory->GovernanceDAO: Create a new DAO
note right
UI passes name, admin, 
token, godHolder
quorumThreshold, votingDelay, votingPeriod
end note
GovernanceDAO->GovernanceDAO: creates instance of GovernorTokenTransfer contract
GovernanceDAO->GovernanceDAO: Create new DAO instance
GovernanceDAO->DAOFactory: Returns the new DAO address
DAOFactory->DAOFactory: Save the address in its state 
DAOFactory->UI: Result back to UI
note left
UI now has addresses of
new DAO, token transfer governor contracts
end note
UI->GovernanceDAO: Create a token transfer proposal
GovernanceDAO->GovernorTokenTransfer: Create a new proposal
GovernorTokenTransfer->GovernorTokenTransfer: Creates proposal
GovernorTokenTransfer->GovernanceDAO: Gives new proposal address
GovernanceDAO->GovernanceDAO: Save proposal address in its state
GovernanceDAO->UI: Share new proposal address to UI
UI->GovernorTokenTransfer: Invokes voting functions etc
@enduml