@startuml UpgradeFlow
Developer->GitHub : Push to develop branch
GitHub->GitHub: Identify the changed contracts
GitHub->testnet: Deploy the new version UpgradeGovernorSmartContract
GitHub->UpgradeGovernorSmartContract: Create a new aproposal 
UI->UpgradeGovernorSmartContract: Shows proposals on UI
UI->UpgradeGovernorSmartContract: User having GOD token votes on that proposal
UI->UpgradeGovernorSmartContract: Execute the proposal  
UpgradeGovernorSmartContract-> UpgradeGovernorSmartContract: Update the proxy's logic contract address
GitHubActionJob->UpgradeGovernorSmartContract: Query the latest logic address
GitHubActionJob->TransparentProxyOfChangedLogicContract: calls the upgradeTo function and change the implementation
@enduml
