name: Deploy a new contract to testnet
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: Run the Docker image using commit message
      run: docker run --env COMMIT_MESSAGE="${{ github.event.head_commit.message }}" --env OPERATOR_ID=0.0.47710057 --env OPERATOR_KEY=3030020100300706052b8104000a04220420d38b0ed5f11f8985cd72c8e52c206b512541c6f301ddc9d18bd8b8b25a41a80f --env ADMIN_ID=0.0.47710057 --env ADMIN_KEY=3030020100300706052b8104000a04220420d38b0ed5f11f8985cd72c8e52c206b512541c6f301ddc9d18bd8b8b25a41a80f --env TREASURE_ID=0.0.47645191 --env TREASURE_KEY=308ed38983d9d20216d00371e174fe2d475dd32ac1450ffe2edfaab782b32fc5  my-image-name:latest
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: contracts.json
        commit_message: Updating contract record
        push_options: '--force'
        skip_dirty_check: false
        skip_fetch: true
        skip_checkout: true
        create_branch: false 
      name: "Run if changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: echo "Changes!"