name: Deploy a contract to testnet
on:
  workflow_dispatch:
    inputs:
      contractName:
        description: 'Name that represent the contract to deploy.'
        default: 'swapContract'
        required: true
        type: string